name: Build Debug APK

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant gradlew permission
      run: chmod +x ./gradlew

    - name: Get version from gradle
      run: echo "VERSION=$(grep -oP 'versionName\s*=\s*"\K[^"]+' app/build.gradle.kts)" >> $GITHUB_ENV

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Rename and Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: exammod-debug-${{ github.sha }}
        path: app/build/outputs/apk/debug/app-debug.apk
