name: Release Build

on:
  push:
    tags:
      - 'v*' # Trigger saat tag v* dibuat (contoh: v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant gradlew permission
      run: chmod +x ./gradlew

    - name: Get version from gradle
      run: echo "VERSION=$(grep -oP 'versionName\s*=\s*"\K[^"]+' app/build.gradle.kts)" >> $GITHUB_ENV

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Rename APK
      run: |
        mkdir -p release_apk
        mv app/build/outputs/apk/release/app-release.apk "release_apk/exammod-v${{ env.VERSION }}.apk"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: release_apk/*.apk
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
